"""
Django settings for uzshop_config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q8x_ncm64_2r7_v!x%8)!^#u-i2b9x&8ejent5185uwq^9985!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# Qo'shimchlar ham bor
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'products',
    'bag',
    'checkout',
    'allauth',
    'allauth.account',
    'orders',                        
    'paytechuz.integrations.django',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'uzshop_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bag.contexts.bag_contents',
            ],
        },
    },
]

WSGI_APPLICATION = 'uzshop_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'uzshop_db',
        'USER': 'uzshop_user',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/



# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = 'products'
ACCOUNT_EMAIL_VERIFICATION = 'none' 
LOGOUT_REDIRECT_URL = '/accounts/login/'

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# PAYTECHUZ = {
#     'PAYME': {
#         'PAYME_ID': 'your_payme_id',
#         'PAYME_KEY': 'your_payme_key',
#         'ACCOUNT_MODEL': 'orders.models.Order',
#         'ACCOUNT_FIELD': 'id',
#         'AMOUNT_FIELD': 'amount',
#         'ONE_TIME_PAYMENT': True,
#         'IS_TEST_MODE': True,
#     },
#     'CLICK': {
#         'SERVICE_ID': 'your_service_id',
#         'MERCHANT_ID': 'your_merchant_id',
#         'MERCHANT_USER_ID': 'your_merchant_user_id',
#         'SECRET_KEY': 'your_secret_key',
#         'ACCOUNT_MODEL': 'orders.models.Order',
#         'IS_TEST_MODE': True,
#     },
#     'UZUM': {
#         'MERCHANT_ID': 'your_uzum_merchant_id',
#         'MERCHANT_KEY': 'your_uzum_merchant_key',
#         'ACCOUNT_MODEL': 'orders.models.Order',
#         'IS_TEST_MODE': True,
#     },
# }
# Litzensiya kaliti hali hal qilinmadi
# export PAYTECH_LICENSE_API_KEY="sizning_litsenziya_kalitingiz"

JAZZMIN_SETTINGS = {
    "site_title": "UzShop Admin",
    "site_header": "UzShop",
    "site_brand": "UzShop",
    "welcome_sign": "UzShop boshqaruv paneliga xush kelibsiz",
    "copyright": "UzShop",
    "show_ui_builder": True,
}